# Module scaffolded via skyvafnir-module-template by
# Author: jonorrikristjansson
# Version: 0.1.0
# Timestamp: 2024-01-14T16:44:10

################################################################################
## NOTE: Do not edit this file directly. It should be uniform across modules. ##
################################################################################
module "defaults" {
  source   = "../../modules/skyvafnir/defaults"
  tags     = var.tags
  caller   = basename(path.module)
  org_code = var.org_code
  tier     = var.tier
  instance = var.instance
}
