# Module scaffolded via skyvafnir-module-template by
# Author: jonorrikristjansson
# Version: 0.1.0
# Timestamp: 2024-01-17T13:33:48

################################################################################
## NOTE: Do not edit this file directly. It should be uniform across modules. ##
################################################################################

module "defaults" {
  source                = "../../skyvafnir/defaults"
  resource_abbreviation = local.resource_abbreviation
  tags                  = var.tags
  caller                = basename(path.module)
  org_code              = var.org_code
  tier                  = var.tier
  instance              = var.instance
}

locals {
  # tflint-ignore: terraform_unused_declarations
  tags = module.defaults.tags
}
