# Module scaffolded via skyvafnir-module-template by
# Author: Skyvafnir

variable "resource_abbreviation" {
  type        = string
  description = <<DESC
    The abbreviation for the resource.  This is used to generate the resource name.
  DESC
}

variable "org_code" {
  type        = string
  description = <<DESC
    Organization code.
  DESC
}

variable "tier" {
  type        = string
  description = <<DESC
    Tier of the environment.
  DESC
}

variable "instance" {
  type        = string
  description = <<DESC
    Purpose or identifier for the application, workload or service.
  DESC
}

variable "tags" {
  type        = map(string)
  description = <<DESC
    Any tags that should be present on created resources. Will get merged with local.default_tags
  DESC
  default     = {}
}

variable "default_tag_override" {
  type        = map(string)
  description = <<DESC
    Any tags that should be present on created resources. Will override local.default_tags
  DESC
  default     = null
}

variable "append_random_pet" {
  type        = bool
  description = <<DESC
    Whether to append a random pet name to the resource name.
  DESC
  default     = false
}

variable "caller" {
  type        = string
  description = <<DESC
    The name of the caller of the module. (best supplied via `basename(path.module)`.
    Populates the `part-of-module` tag.
  DESC
}

variable "prefix" {
  type        = string
  default     = ""
  description = <<DESC
    Prefix to add to the resource name instead of the `org_code`.
  DESC
}

variable "include_tier_in_names" {
  type        = bool
  default     = true
  description = <<DESC
    Whether names should include tier.
    I.e. if `tiered_naming = false` will result in a resource name like `[org_code]-[instance]`
    while `tiered_naming = true` will result in a resource name like `[org_code]-[instance]-[tier]`
  DESC
}

variable "provisioned_by" {
  type        = string
  default     = "skyvafnir-terraform"
  description = <<DESC
    The name of the tool that is provisioning the resource.
    Populates the `provisioned-by` tag.
  DESC

}
variable "iac_support_email" {
  type        = string
  default     = "support@skyvafnir.cloud"
  description = <<DESC
    An email address. Used to populate the `iac_support_email` tag.
  DESC
}

variable "name_override" {
  type        = string
  description = <<DESC
  Override the name of the resource. This ia an escape hatch in case the name generated by the module is not suitable.
  DESC
  default     = null

}
