# Module scaffolded via skyvafnir-module-template by
# Author: Skyvafnir

## Generic vars

variable "org_code" {
  description = "Organization code"
  type        = string
}

variable "instance" {
  description = "For what purpose is this module being used?"
  type        = string
}

variable "tier" {
  description = "Tier of the environment"
  type        = string
}

variable "tags" {
  description = "Any tags that should be present on created resources. Will get merged with local.default_tags"
  type        = map(string)
  default     = {}
}

variable "resource_group_info" {
  description = "Name and Location of the Resource Group"
  type = object({
    id       = optional(string)
    name     = string
    location = string
  })
}

## Storage Account vars
variable "account_tier" {
  description = " Defines the Tier to use for this storage account. Valid options are Standard and Premium. For BlockBlobStorage and FileStorage accounts only Premium is valid. Changing this forces a new resource to be created. Defaults to Standard."
  type        = string
  default     = "Standard"
}

variable "account_kind" {
  description = "Defines the Kind of account. Valid options are BlobStorage, BlockBlobStorage, FileStorage, Storage and StorageV2. Defaults to StorageV2."
  type        = string
  default     = "StorageV2"
}

variable "account_replication_type" {
  description = "Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS"
  type        = string
  default     = "LRS"
}

variable "account_soft_delete_retention_days" {
  type        = number
  description = "The number of days that the soft-deleted blob will be retained. Must be set between 1 and 365. Set to 0 to disable soft delete. Defaults to 0."
  default     = 0
}

variable "logging_properties" {
  type = object({
    delete                = bool
    read                  = bool
    version               = string
    write                 = bool
    retention_policy_days = number
  })
  description = "The logging properties for the storage account"
  default     = null
}

variable "identity" {
  type = object({
    type         = optional(string, "SystemAssigned")
    identity_ids = optional(list(string), null)
  })
  description = "The identity block for the storage account"
  default     = null
}

variable "public_network_access_enabled" {
  type        = bool
  description = "Controls whether data may be accessed from public networks."
  default     = true
}

variable "min_tls_version" {
  type        = string
  description = "The minimum TLS version to use for the storage account"
  default     = "TLS1_2"
}

variable "storage_container_config" {
  description = "Configuration for the storage containers"
  type = object({
    name                  = string
    container_access_type = string
    metadata              = map(string)
  })
  default = null
}

variable "storage_account_name_override" {
  type        = string
  description = "Override the storage account name. If not set, the storage account name will be autogenerated based on the org_code, instance and tier."
  default     = null
}
