################################################################################
## NOTE: Do not edit this file directly. It should be uniform across modules. ##
################################################################################

module "defaults" {
  source                = "../../../skyvafnir/defaults"
  resource_abbreviation = local.resource_abbreviation
  tags                  = var.tags
  caller                = basename(path.module)
  org_code              = var.org_code
  tier                  = var.tier
  instance              = var.instance
}

locals {
  tags = module.defaults.tags
}
