# Module scaffolded via skyvafnir-module-template by
# Author: jonorrikristjansson
# Version: 0.1.0
# Timestamp: 2024-01-04T10:40:16

################################################################################
## NOTE: Do not edit this file directly. It should be uniform across modules. ##
################################################################################

module "defaults" {
  source                = "../../skyvafnir/defaults"
  tags                  = var.tags
  caller                = basename(path.module)
  org_code              = var.org_code
  tier                  = var.tier
  instance              = var.instance
  resource_abbreviation = local.resource_abbreviation
}
